version: '3.8'

services:
  db: # Сервис базы данных (без изменений)
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ExpenseTrackerDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api: # Сервис для вашего API
    build:
      context: .               # Контекст сборки - корневая папка
      dockerfile: Dockerfile   # Dockerfile теперь в корне
    ports:
      - "5024:80"
      - "7024:443"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ExpenseTrackerDb;Username=user;Password=password"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: