version: '3.8'

services:
  db:
    # ... (ваш сервис db остается без изменений) ...
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ExpenseTrackerDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ef_cli: # <--- НОВЫЙ СЕРВИС ДЛЯ EF CORE CLI
    build:
      context: .
      dockerfile: Dockerfile.ef # <--- Используем новый Dockerfile.ef
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ExpenseTrackerDb;Username=user;Password=password"
    depends_on:
      - db
    # Нет портов, так как это не работающий сервис, а просто для команд

  api:
    # ... (ваш сервис api остается без изменений) ...
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5024:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ExpenseTrackerDb;Username=user;Password=password"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: